<a href="https://colab.research.google.com/github/Rediquiest/MyGitProject/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D0%B0%20%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0%20%E2%84%961%20%D0%9A%D0%A1%D0%92%D0%94%20%D0%A8%D0%B5%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE%20%D0%A4%D0%86%D0%A2%203-11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1)Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
import numpy as np
vector = np.arange(1,21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#2)Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix4x4 = np.ones((4,4))
print(matrix4x4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#3)Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
matrix_random = np.random.uniform(-1,1,(5,5))
print(matrix_random)

[[-0.3821991   0.51546033 -0.24940369  0.40912872  0.99975853]
 [ 0.22704888  0.4424084  -0.93545817  0.11550075 -0.33741488]
 [-0.18114915 -0.80779725  0.60204718 -0.33296048  0.29139248]
 [-0.61523912  0.81084614  0.6450311   0.12071663  0.28470692]
 [ 0.01450603 -0.95132272  0.1421229  -0.53725749  0.13800427]]


In [ ]:
#4)Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix_random3x3 = np.random.uniform(0,1,(3,3))
print(matrix_random3x3)

[[0.10251314 0.2656902  0.70283821]
 [0.11544248 0.98344589 0.45327775]
 [0.7414045  0.45320631 0.85860156]]


In [ ]:
#5)Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання,
#віднімання та множення.
vector1 = np.random.randint(1, 21, 6)
vector2 = np.random.randint(1, 21, 6)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Додавання: ", vector1 + vector2)
print("Віднімання: ", vector1 - vector2)
print("Множення: ", vector1 * vector2)

Вектор 1: [ 9 16 18 10  3 19]
Вектор 2: [ 8  1 14 10  8 18]
Додавання:  [17 17 32 20 11 37]
Віднімання:  [ 1 15  4  0 -5  1]
Множення:  [ 72  16 252 100  24 342]


In [ ]:
#6)Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
matrix_a = np.random.randint(1, 6, (3,2))
matrix_b = np.random.randint(1, 6, (2,4))
matrix_mnozh = np.dot(matrix_a,matrix_b)
print("Матриця A (3x2):")
print(matrix_a)
print("Матриця B (2x4):")
print(matrix_b)
print("Добуток матриць A і B:")
print(matrix_mnozh)


Матриця A (3x2):
[[1 2]
 [3 3]
 [1 5]]
Матриця B (2x4):
[[5 5 1 1]
 [1 2 3 5]]
Добуток матриць A і B:
[[ 7  9  7 11]
 [18 21 12 18]
 [10 15 16 26]]


In [ ]:
#7)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix3x3 = np.random.rand(3,3)
print("\nМатриця 3x3:")
print(matrix3x3)
print("Транспонована матриця:")
print(matrix3x3.T)


Матриця 3x3:
[[0.89525673 0.71149991 0.66168205]
 [0.87440539 0.29251499 0.5899629 ]
 [0.93502459 0.15130298 0.36371512]]
Транспонована матриця:
[[0.89525673 0.87440539 0.93502459]
 [0.71149991 0.29251499 0.15130298]
 [0.66168205 0.5899629  0.36371512]]


In [ ]:
#8)Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrixa = np.random.randint(1, 11, (3, 3))
matrixb = np.random.randint(1, 11, (3, 3))
print("Матриця A:")
print(matrixa)
print("Матриця B")
print(matrixb)
print("Різниця:")
print(matrixa - matrixb)

Матриця A:
[[10  2  5]
 [ 8  7  3]
 [ 2  8  2]]
Матриця B
[[8 7 3]
 [2 3 4]
 [5 8 8]]
Різниця:
[[ 2 -5  2]
 [ 6  4 -1]
 [-3  0 -6]]


In [ ]:
#9)Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
matrix_3x3a = np.random.randint(-5, 6, (3, 3))
matrix_3x3b = np.random.randint(-5, 6, (3, 3))
print("Матриця A:")
print(matrix_3x3a)
print("Матриця B:")
print(matrix_3x3b)
print("Добуток:")
print(np.dot(matrix_3x3a, matrix_3x3b))

Матриця A:
[[-5 -1 -4]
 [ 4  4 -4]
 [-4 -2  0]]
Матриця B:
[[-2 -1 -1]
 [ 4  4  4]
 [ 0  1 -5]]
Добуток:
[[ 6 -3 21]
 [ 8  8 32]
 [ 0 -4 -4]]


In [ ]:
#10)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix_3x3 = np.random.uniform(-1, 1, (3, 3))
row_sums = matrix_3x3.sum(axis=1).reshape(-1, 1)
print(matrix_3x3)
print("Вектор-стовпчик сум елементів кожного рядка:")
print(row_sums)

[[-0.56634011  0.17087871  0.97652688]
 [ 0.0189687   0.738545   -0.35421128]
 [ 0.95330639  0.61850383  0.2054919 ]]
Вектор-стовпчик сум елементів кожного рядка:
[[0.58106548]
 [0.40330241]
 [1.77730212]]
